name: Deploy Website

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install pnpm
        run: corepack enable

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'
          cache-dependency-path: website/pnpm-lock.yaml

      - name: Install dependencies
        run: cd website && pnpm install

      - name: Build Site
        run: cd website && npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: website/dist
          clean: false
