name: Manual

on:
  workflow_dispatch:
    inputs:
      product:
        description: 'product name of which to bench'
        type: choice
        default: 'ALL'
        options:
          - ALL
          - MODERNJS_FRAMEWORK
          - MODERNJS_MODULE
          - RSBUILD
          - RSPRESS
      case:
        description: 'case name of which to bench'
        type: choice
        default: 'ALL'
        options:
          - app-minimal
          - app-initial
          - app-initial-rspack
          - app-tailwind
          - app-ssr
          - app-ssg
          - app-bff-koa
          - app-arco-pro
          - app-arco-pro-swc
          - app-arco-pro-esbuild
          - app-arco-pro-rspack
      commitId:
        description: 'commitId of your repo'
      onlyInstallSize:
        description: "If only want install size, set to 'true'"

jobs:
  benchmark:
    strategy:
      matrix:
        include:
          - case: app-minimal
            product: MODERNJS_FRAMEWORK
          - case: app-initial
            product: MODERNJS_FRAMEWORK
          - case: app-initial-rspack
            product: MODERNJS_FRAMEWORK
          - case: app-tailwind
            product: MODERNJS_FRAMEWORK
          - case: app-ssr
            product: MODERNJS_FRAMEWORK
          - case: app-ssg
            product: MODERNJS_FRAMEWORK
          - case: app-bff-koa
            product: MODERNJS_FRAMEWORK
          - case: app-arco-pro
            product: MODERNJS_FRAMEWORK
          - case: app-arco-pro-swc
            product: MODERNJS_FRAMEWORK
          - case: app-arco-pro-esbuild
            product: MODERNJS_FRAMEWORK
          - case: app-arco-pro-rspack
            product: MODERNJS_FRAMEWORK

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Pnpm
        run: corepack enable && pnpm -v

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm run install:scripts

      - name: 🚀 Run all benchmark
        if: ${{ github.event.inputs.product == 'ALL' }}
        run: cd scripts && ONLY_INSTALL_SIZE=${{ github.event.inputs.onlyInstallSize }} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} COMMIT_ID=${{ github.event.inputs.commitId }} pnpm start ${{ matrix.product }} ${{ matrix.case }}

      - name: 🚀 Run specified product benchmark
        if: ${{ github.event.inputs.product != 'ALL' && github.event.inputs.case == 'ALL' && github.event.inputs.product == matrix.product }}
        run: cd scripts && ONLY_INSTALL_SIZE=${{ github.event.inputs.onlyInstallSize }} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} COMMIT_ID=${{ github.event.inputs.commitId }} pnpm start ${{ matrix.product }} ${{ matrix.case }}

      - name: 🚀 Run specified case benchmark
        if: ${{ github.event.inputs.product != 'ALL' && github.event.inputs.case != 'ALL' && github.event.inputs.product == matrix.product && github.event.inputs.case == matrix.case }}
        run: cd scripts && ONLY_INSTALL_SIZE=${{ github.event.inputs.onlyInstallSize }} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} COMMIT_ID=${{ github.event.inputs.commitId }} pnpm start ${{ matrix.product }} ${{ matrix.case }}

      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update data
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: data
          target-folder: data
          git-config-name: gh-pages-bot
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          clean: false
