name: Manual

on:
  workflow_dispatch:
    inputs:
      commitId:
        description: 'commitId of modern.js repo'
      onlyInstallSize:
        description: "If only want install size, set to 'true'"

jobs:
  benchmark:
    strategy:
      matrix:
        case:
          - mwa-minimal
          - mwa-minimal-v2
          - mwa-initial
          - mwa-initial-v2
          - mwa-tailwind
          - mwa-tailwind-v2
          - mwa-ssr
          - mwa-ssr-v2
          - mwa-ssg
          - mwa-ssg-v2
          - mwa-bff-koa
          - mwa-bff-koa-v2
          - mwa-arco-pro
          - mwa-arco-pro-v2
          - mwa-arco-pro-esbuild
          - mwa-arco-pro-esbuild-v2

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Pnpm
        run: npm install -g pnpm@^7

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: .turbo
          key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}-${{ github.ref_name }}-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: scripts/pnpm-lock.yaml

      - name: wireit cache
        uses: google/wireit@setup-github-actions-caching/v1

      - name: Install Dependencies
        run: cd scripts && pnpm install

      - name: 🚀 Run benchmark
        run: cd scripts && ONLY_INSTALL_SIZE=${{ github.event.inputs.onlyInstallSize }} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} COMMIT_ID=${{ github.event.inputs.commitId }} pnpm start ${{ matrix.case }}

      - name: Update data
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: data
          target-folder: data
          clean: false
