name: Scheduled

on:
  schedule:
    - cron: '0 1,13 * * *'

jobs:
  benchmark:
    strategy:
      matrix:
        case:
          - mwa-minimal-v2
          - mwa-initial-v2
          - mwa-tailwind-v2
          - mwa-ssr-v2
          - mwa-ssg-v2
          - mwa-bff-koa-v2
          - mwa-arco-pro-v2
          - mwa-arco-pro-esbuild-v2

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Pnpm
        run: npm install -g pnpm@^7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: scripts/pnpm-lock.yaml

      - name: Turbo Cache
        id: turbo-cache
        uses: actions/cache@v2
        with:
          path: modern.js/.turbo
          key: turbo-${{ github.ref_name }}-${{ github.sha }}
          restore-keys: |
              turbo-${{ github.ref_name }}-

      - name: Install Dependencies
        run: cd scripts && pnpm install

      - name: 🚀 Run benchmark
        run: cd scripts && GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} pnpm start ${{ matrix.case }}

      - name: Update data
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: data
          target-folder: data
          clean: false
