name: Scheduled

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  benchmark:
    continue-on-error: true
    strategy:
      max-parallel: 2
      matrix:
        include:
          - case: app-minimal
            product: MODERNJS_FRAMEWORK
          - case: app-initial
            product: MODERNJS_FRAMEWORK
          - case: app-initial-rspack
            product: MODERNJS_FRAMEWORK
          - case: app-tailwind
            product: MODERNJS_FRAMEWORK
          - case: app-ssr
            product: MODERNJS_FRAMEWORK
          - case: app-ssg
            product: MODERNJS_FRAMEWORK
          - case: app-bff-koa
            product: MODERNJS_FRAMEWORK
          - case: app-arco-pro
            product: MODERNJS_FRAMEWORK
          - case: app-arco-pro-swc
            product: MODERNJS_FRAMEWORK
          - case: app-arco-pro-esbuild
            product: MODERNJS_FRAMEWORK
          - case: app-arco-pro-rspack
            product: MODERNJS_FRAMEWORK
          - case: module-initial
            product: MODERNJS_MODULE
          - case: module-library
            product: MODERNJS_MODULE
          - case: module-library-sourcemap
            product: MODERNJS_MODULE
          - case: module-library-noautoexternal
            product: MODERNJS_MODULE
          - case: module-library-minify-esbuild
            product: MODERNJS_MODULE
          - case: module-library-minify-terser
            product: MODERNJS_MODULE
          - case: module-component
            product: MODERNJS_MODULE
          - case: rspress-minimal
            product: RSPRESS
          - case: rspress-website
            product: RSPRESS
          - case: rspress-website-mdxjs
            product: RSPRESS
          - case: rsbuild-react
            product: RSBUILD
          - case: rsbuild-vue2
            product: RSBUILD
          - case: rsbuild-vue3
            product: RSBUILD
          - case: rsbuild-lit
            product: RSBUILD
          - case: rsbuild-svelte
            product: RSBUILD
          - case: rsbuild-vanilla
            product: RSBUILD
          - case: rsbuild-arco-pro
            product: RSBUILD

    runs-on: ${{ fromJSON(vars.SELF_LINUX_LABELS || '"ubuntu-latest"') }}

    steps:
      - name: Print runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Pnpm
        run: corepack enable && pnpm -v

      - name: Cache pnpm cache
        uses: actions/cache@v3
        if: ${{ startsWith(runner.name, 'GitHub Actions') }}
        with:
          path: |
            ~/.cache/pnpm
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        run: pnpm run install:scripts

      - name: 🚀 Run benchmark
        run: cd scripts && GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} pnpm start ${{ matrix.product }} ${{ matrix.case }}

      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync

      - name: Update data
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: data
          target-folder: data
          git-config-name: gh-pages-bot
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          clean: false
