name: Scheduled

on:
  schedule:
    - cron: '0 1,13 * * *'
  workflow_dispatch:

jobs:
  benchmark:
    strategy:
      matrix:
        include:
          - case: app-minimal
            product: MODERNJS_FRAMEWORK
          - case: app-initial
            product: MODERNJS_FRAMEWORK
          - case: app-initial-rspack
            product: MODERNJS_FRAMEWORK
          - case: app-tailwind
            product: MODERNJS_FRAMEWORK
          - case: app-ssr
            product: MODERNJS_FRAMEWORK
          - case: app-ssg
            product: MODERNJS_FRAMEWORK
          - case: app-bff-koa
            product: MODERNJS_FRAMEWORK
          - case: app-arco-pro
            product: MODERNJS_FRAMEWORK
          - case: app-arco-pro-swc
            product: MODERNJS_FRAMEWORK
          - case: app-arco-pro-esbuild
            product: MODERNJS_FRAMEWORK
          - case: app-arco-pro-rspack
            product: MODERNJS_FRAMEWORK
          - case: module-initial
            product: MODERNJS_MODULE
          - case: module-library
            product: MODERNJS_MODULE
          - case: module-library-sourcemap
            product: MODERNJS_MODULE
          - case: module-library-noautoexternal
            product: MODERNJS_MODULE
          - case: module-library-minify-esbuild
            product: MODERNJS_MODULE
          - case: module-library-minify-terser
            product: MODERNJS_MODULE

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install Pnpm
        run: corepack enable && pnpm -v

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm run install:scripts

      - name: 🚀 Run benchmark
        run: cd scripts && GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} pnpm start ${{ matrix.product }} ${{ matrix.case }}

      - name: Setup git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update data
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: data
          target-folder: data
          git-config-name: gh-pages-bot
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          clean: false
